### ISSUE TITLE
Arithmetic operation in @media queries

### ISSUE THREAD

**Issue by ojullien** [Chalarangelo/mini.css#110] opened 2017-10-26 16:40 UTC
* Framework Version: mini.css v2.3.7
* Flavor used: mini-default
* Operating System/Browser: Debian 9.2, Sass 3.5.2 (Bleeding Edge), Compass 1.0.3 (Polaris)
* Code to reproduce: @media screen and (max-width: 768px (-1px)) {
* Bug description:

Arithmetic operation like ( in _utility_mixins.scss file )
    @media screen and (max-width: #{$hidden-medium-breakpoint}-1px) {
is translated to 
    @media screen and (max-width: 768px (-1px)) {
which goes wrong in a web browser ( like Chrome 62.0.3202.62 )    

If we modify
    @media screen and (max-width: #{$hidden-medium-breakpoint}-1px) {
to
    @media screen and (max-width: #{$hidden-medium-breakpoint - 1}) {
we obtain
    @media screen and (max-width: 767px) {
which goes right
    
I think it is about interpolating variables

**Comment by Chalarangelo** [comment] 2017-10-26 16:43
Whoops, my bad! Thanks for noticing. This will be fixed asap. Expect another hotfix!

**Comment by Chalarangelo** [comment] 2017-10-27 07:43
**Update:** Both my setups that use [`node-sass`](https://github.com/sass/node-sass) compile this as expected, resulting in `767px` instead of `768px (-1px)`. This could be a problem with the specific version of Sass. It might require further investigating, as well as some more input from people if this really is a common issue. I am going to test this further and get back to you.

**Comment by ojullien** [comment] 2017-10-29 20:00
I'm using ruby-sass. I'll try node-sass. I'll tell you. Great job anyway.



Envoyé depuis mon smartphone Samsung Galaxy.


-------- Message d'origine --------
De : Angelos Chalaris <notifications@github.com>
Date : 27/10/2017 09:44 (GMT+01:00)
À : "Chalarangelo/mini.css" <mini.css@noreply.github.com>
Cc : ojullien <olivierjullien@outlook.com>, Author <author@noreply.github.com>
Objet : Re: [Chalarangelo/mini.css] Arithmetic operation in @media queries (#110)


Update: Both my setups that use node-sass<https://github.com/sass/node-sass> compile this as expected, resulting in 767px instead of 768px (-1px). This could be a problem with the specific version of Sass. It might require further investigating, as well as some more input from people if this really is a common issue. I am going to test this further and get back to you.

**Comment by ojullien** [comment] 2017-11-02 14:45
I confirm, works well with node v6.11.5, npm 5.5.1, node-sass 4.5.3
The bug appears with gem sass (v3.5.2) from Ruby

**Comment by Chalarangelo** [comment] 2017-11-02 15:19
I'm marking this as resolved, provided that everything works as intended using the listed `devDependencies` in node. Thanks for testing this out!

**Closed as completed by Chalarangelo** 2017-11-02 15:19 UTC
Labels: bug, Fermion, browser/environment specific, good first issue
