### ISSUE TITLE
radio button misalignment for narrow widths

### ISSUE THREAD

**Issue by aguaviva** [Chalarangelo/mini.css#107] opened 2017-10-21 09:55 UTC
This is the radio being displayed properly
![image](https://user-images.githubusercontent.com/5200915/31850668-7946b792-b656-11e7-91ce-231eed898e3b.png)

When I shrink the width I get this layout
![image](https://user-images.githubusercontent.com/5200915/31850675-93baff34-b656-11e7-9f78-68ab31f4abf8.png)

**Comment by Chalarangelo** [comment] 2017-10-21 10:04
Thanks for reporting this. I will be looking into this in the future, but right now the main focus is on getting the first **Gluon** alpha up and running. 

This is definitely a problem that I want to get resolved as soon as I can, so it's on the top of the list of fixes that will be released for **Fermion**. I am marking as `help wanted` and `good first issue` in case anyone wants to take care of this for me. Please submit your PRs against the `fermion.v3` branch, **not** the `master` branch. Thanks!

**Comment by Chalarangelo** [comment] 2017-10-23 09:12
## Update

I tried to reproduce your problem and created [this Codepen](https://codepen.io/chalarangelo/pen/mBYyMx?editors=1010). 

![Demo](https://user-images.githubusercontent.com/8281875/31880932-af95724e-b7ea-11e7-8ec0-5c67c823c5a6.PNG)

Firefox displays this as intended, however Chrome doesn't particularly like it.

**Comment by Chalarangelo** [comment] 2017-10-23 09:41
## Update

I'm pretty much clueless about this and I feel like this is something that requires an immediate fix. I opened a [SO question](https://stackoverflow.com/q/46886199/1650200), which will hopefully help enlighten us a bit about what is really going on.

**Closed as completed** 2017-10-23 11:21 UTC
Labels: bug, help wanted, mobile, Fermion, webkit, browser/environment specific, good first issue
