### ISSUE TITLE
Sticky header is broken with Chrome on Android

### ISSUE THREAD

**Issue by yunyu** [Chalarangelo/mini.css#60] opened 2017-03-15 00:13 UTC
Mobile screenshot (note weird positioning, empty space on top and left): 

![](http://i.imgur.com/GyGdSx3.png)

Desktop screenshot (looks normal-ish):

![](https://i.imgur.com/ehDvBNo.png)

**Comment by Chalarangelo** [comment] 2017-03-15 06:32
I managed to reproduce this in the latest version of Chrome on Android. Thanks for reporting this! I will try to figure out why it's happening, although a quick Google search didn't seem to yield any results. The `<nav>` element was due for a rework to deal with its responsiveness anyway (as many people have complained about the way it behaves, which is the "awkward" scrolling), so I will be looking into this very soon. Hopefully, the bug is not on Chrome's side, so this can be resolved eventually.

**Comment by Chalarangelo** [comment] 2017-03-15 08:11
**Update:** Bug spotted in desktop version of Chrome as well. This will make it a whole lot easier figuring out what the cause is.

**Comment by Chalarangelo** [comment] 2017-03-15 08:41
Opened a [question on SO](http://stackoverflow.com/q/42804714/1650200) to figure out a solution. The problem can be reproduced easily in Chrome and seems so far to be a bug on their end. Further investigation is required.

**Comment by Chalarangelo** [comment] 2017-03-15 09:40
### Provided solution

As stated in [this answer on SO](http://stackoverflow.com/a/42805354/1650200), the bug can be fixed on Chrome 56, using:

```
body {
    overflow: hidden;
}
```

The bug cannot be reproduced in Chrome 57 and, as stated in the docs, the `.sticky` class might not be compatible with all browsers. If you want to support legacy browsers and OSs, please avoid using it or try using the above fix.

### Further action

This issue will be closed, however I will add a note in the `.sticky` class's section in the docs to inform people that this bug may be present in certain versions of Chrome. The fix provded above will not be deployed in the main version of **mini.css** as it might cause other unexpected complications with certain components.

### Technical documentation

This bug seems to be partially due to the way Chrome renders `box-shadow` in combination with `position: sticky`. It seems like Chrome 57 had this issue resolved, however it might pop up again in the future. Refer to the provided links in this issue for more information.

**Closed as completed by Chalarangelo** 2017-03-15 09:40 UTC
Labels: bug, mobile
