### ISSUE TITLE
Declare column layout for children

### ISSUE THREAD

**Issue by naasking** [Chalarangelo/mini.css#53] opened 2016-12-24 16:19 UTC
[Picnic CSS's grids have a nice feature](http://picnicss.com/documentation#grids) to declare that child content fits into a certain number of columns, without having to specify the widths on each child. For instance, in Picnic:

    <div class="flex three demo">
      <div><span>1</span></div>
      <div><span>2</span></div>
      <div><span>3</span></div>
      <div><span>4</span></div>
      <div><span>5</span></div>
    </div>

would look like this in mini.css (correct me if I'm wrong!):

    <div class="row">
      <div class="col-sm-4"><span>1</span></div>
      <div class="col-sm-4"><span>2</span></div>
      <div class="col-sm-4"><span>3</span></div>
      <div class="col-sm-4"><span>4</span></div>
      <div class="col-sm-4"><span>5</span></div>
    </div>

As you can imagine, a large form with a lot of children requires considerably more work to write and update. With Picnic's grids, you can change the layout from "three" columns to "four" at a breakpoint of 800px by only adding "four-800" to the top-level, but with mini.css you have to change every child.

I don't like how Picnic provides breakpoints at every 100px increment, but I think the overall idea for a small set of breakpoints is solid.

**Comment by Chalarangelo** [comment] 2016-12-24 16:27
This is an overall good idea, although I will implement it so that either the previous structure is used **or** both that and the one you suggest. Supporting both in the same flavor can bloat the file size a little bit, so the Sass files will have a flag to include this feature or not in a flavor.

Personally, I find this feature reasonably useful and I believe I can use it to make my life a lot easier by predefining certain layouts. This could be a candidate for **v2.1**, but it might get pushed back for later.

**Comment by Chalarangelo** [comment] 2017-01-06 17:22
The system described above has been implemented and is scheduled to ship with [v2.1.0](https://github.com/Chalarangelo/mini.css/milestone/6) sometime next month. The issue is resolved and will close when the current development branch is merged into the `master` branch. Thank you for the suggestion!

**Closed as completed** 2017-02-16 18:58 UTC
Labels: enhancement, Fermion
